version: "3.5"

volumes:
  logica-sandbox-volume:

services:

  keycloak:
    image: jboss/keycloak
    volumes:
      - "./realm_properties.json:/etc/security/realm_properties.json"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/etc/security/realm_properties.json
    command: ["-Djboss.http.port=8080", "-Dkeycloak.profile.feature.upload_scripts=enabled"]

  sandbox-mysql:
    image: gopalinteropion/sandbox-mysql
    ports:
      - "3306:3306"
    volumes:
      - logica-sandbox-volume:/var/lib/mysql57
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    container_name: communityedition_sandbox-mysql
    healthcheck:
      test: ["CMD-SHELL", "/wait-for-db.sh"]
      interval: 2s
      timeout: 30s
      retries: 20

  sandbox-manager-api:
    image: gopalinteropion/sandbox-manager-api
    ports:
      - "12000:12000"
    environment:
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_NAME=sandman
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=reference-auth
      - AUTH_PORT=8060
      - API_DSTU2_HOST=dstu2
      - API_STU3_HOST=stu3
      - API_R4_HOST=r4
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  reference-auth:
    image: gopalinteropion/auth
    ports:
      - "8060:8060"
    environment:
      - AUTH_HOST=reference-auth
      - AUTH_PORT=8060
      - DB_NAME=oic
      - DB_HOST=sandbox-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - SHOW_SQL=true
      - API_DSTU2_HOST=dstu2
      - API_DSTU2_PORT=8078
      - API_STU3_HOST=stu3
      - API_STU3_PORT=8079
      - API_R4_HOST=r4
      - API_R4_PORT=8070
      - PATIENT_PICKER_HOST=localhost
      - PATIENT_PICKER_PORT=8094
      - SANDMAN_API_HOST=sandbox-manager-api
      - SANDMAN_API_PORT=12000
      - SPRING_PROFILES_ACTIVE=users-keycloak,local
      - KEYCLOAK_REALM=Development
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_SSL_REQUIRED=none
      - KEYCLOAK_CREDENTIALS=593ada9c-b1dc-444f-a2e6-30cc4add8146
      - KEYCLOAK_LOGOUT_SUCCESS_URL=http://keycloak:8080/auth/realms/Development/protocol/openid-connect/logout?redirect_uri=http://localhost:3001
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  sandbox-manager-prototype:
    image: gopalinteropion/sandbox-manager-prototype
    ports:
      - "3001:3000"

  dstu2:
    image: hspconsortium/api:2.9.0
    ports:
      - "8078:8078"
    environment:
      - SPRING_PROFILES_ACTIVE=dstu2,multitenant
      - API_PORT=8078
      - SANDBOX_NAME=hspc8
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=reference-auth
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  stu3:
    image: hspconsortium/api:2.9.0
    ports:
      - "8079:8079"
    environment:
      - SPRING_PROFILES_ACTIVE=stu3,multitenant
      - API_PORT=8079
      - SANDBOX_NAME=hspc9
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=reference-auth
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  r4:
    image: hspconsortium/api:2.9.0
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=r4,multitenant
      - API_PORT=8070
      - SANDBOX_NAME=hspc10
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=reference-auth
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  static-content:
    image: gopalinteropion/sandbox-ce-static-content
    ports:
      - "8090:80"

  bilirubin-risk-chart:
    image: gopalinteropion/bilirubin-risk-chart-app
    ports:
      - "8086:8086"

  patient-data-manager:
    image: gopalinteropion/patient-data-manager
    ports:
      - "8096:8096"

  ehr-simulator:
    image: hspconsortium/ehr-app:0.6.13
    ports:
      - "3000:3000"

